import { build } from "esbuild";
import { mkdir, readFile, rm } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import publicKey from "../packages/vela/src/public-key.js";

const root = fileURLToPath(new URL("../", import.meta.url));
if (!/^[a-f0-9]{64}$/i.test(publicKey)) {
  throw new Error(
    "The shared Vela public verification key is missing or invalid.",
  );
}
const targets = process.argv.slice(2);
if (!targets.length) targets.push("../billiard", "../tank-turmoil");
for (const directory of targets) {
  const application = path.resolve(root, directory);
  const manifest = JSON.parse(
    await readFile(path.join(application, "src/manifest.json"), "utf8"),
  );
  if (
    typeof manifest.package !== "string" ||
    !/^[a-z][a-z0-9_]*(?:\.[a-z][a-z0-9_]*)+$/.test(manifest.package)
  ) {
    throw new Error("Invalid application package in " + directory);
  }
  const target = path.join(application, "src/activation");
  await mkdir(target, { recursive: true });
  await build({
    stdin: {
      contents: `import device from "@system.device";
import storage from "@system.storage";
import interconnect from "@system.interconnect";
import { createActivation } from "./packages/vela/src/index.js";
export default createActivation(${JSON.stringify(manifest.package)}, ${JSON.stringify(publicKey)}, { device, storage, interconnect });`,
      resolveDir: root,
      sourcefile: "activation-" + path.basename(application) + ".js",
      loader: "js",
    },
    outfile: path.join(target, "index.js"),
    bundle: true,
    platform: "browser",
    format: "esm",
    target: "es2015",
    // Verification-only wearable code has no Node loader or random-source bootstrap.
    define: { require: "undefined" },
    minify: true,
    external: ["@system.device", "@system.storage", "@system.interconnect"],
    legalComments: "eof",
    banner: {
      js: "// Generated by Kovela pnpm prepare:vela from @kovela/vela. Edit the shared source, not this file. Public verification only; no signing seed.",
    },
  });
  await rm(path.join(target, "crypto.js"), { force: true });
  await rm(path.join(target, "public-key.js"), { force: true });
  console.log("Prepared " + manifest.name + " (" + manifest.package + ")");
}
